#!/bin/sh -e

echo "\e[32mThe repo you are using for installing k6 is being shut down as a result of Bintray sunsetting its service on May 1st 2021.\e[0m
The k6 team has created a new package repository where future packages will be published.
In order to upgrade we recommend that you follow the new installation instructions at https://k6.io/docs/getting-started/installation/ and remove the Bintray repository and key as mentioned in the \"Note about Bintray\" section."
exit 1
